/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Model.Fornecedor;
import Model.Usuario;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author vinic
 */
public class CadastarFornecedor extends javax.swing.JInternalFrame {

    Login log = new Login();
    Fornecedor Fornecedor = new Fornecedor();
    TelaPrincipal telaPrinc=new TelaPrincipal();
    Telfone tel=new Telfone();
    

    /**
     * Creates new form cadastrausuaruio
     */
    public CadastarFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_nome_daempresa = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        jText_Email_Fornecedor = new javax.swing.JTextField();
        Jtxt_nome_Empresa = new javax.swing.JTextField();
        btb_Cancelar = new javax.swing.JButton();
        btn_salvarCadastro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        jFormattedCNPJ = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_endereco_fornecedor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        RatioCelular = new javax.swing.JRadioButton();
        RatioFixo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Cadastro de Fornecedor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nome_daempresa.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        lbl_nome_daempresa.setText("Nome da Empresa");
        getContentPane().add(lbl_nome_daempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_email.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        lbl_email.setText("E-mail");
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        lbl_telefone.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        lbl_telefone.setText("Telefone");
        getContentPane().add(lbl_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jText_Email_Fornecedor.setBackground(new java.awt.Color(255, 255, 204));
        jText_Email_Fornecedor.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        getContentPane().add(jText_Email_Fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 610, 31));

        Jtxt_nome_Empresa.setBackground(new java.awt.Color(255, 255, 204));
        Jtxt_nome_Empresa.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        getContentPane().add(Jtxt_nome_Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 480, 30));

        btb_Cancelar.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btb_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vassoura.png"))); // NOI18N
        btb_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btb_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, -1, -1));

        btn_salvarCadastro.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btn_salvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar (1).png"))); // NOI18N
        btn_salvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarCadastroActionPerformed(evt);
            }
        });
        btn_salvarCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_salvarCadastroKeyPressed(evt);
            }
        });
        getContentPane().add(btn_salvarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 20, 10));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        lblCNPJ.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        lblCNPJ.setText("CNPJ");
        getContentPane().add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        jFormattedCNPJ.setBackground(new java.awt.Color(255, 255, 204));
        try {
            jFormattedCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jFormattedCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 220, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 60, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel1.setText("Endereço");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txt_endereco_fornecedor.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txt_endereco_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 810, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 10, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("Cadastro de Fornecedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 80));

        RatioCelular.setText("Celular");
        RatioCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RatioCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RatioCelularFocusLost(evt);
            }
        });
        RatioCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RatioCelularMouseClicked(evt);
            }
        });
        getContentPane().add(RatioCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        RatioFixo.setText("FIXO");
        RatioFixo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RatioFixoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RatioFixoFocusLost(evt);
            }
        });
        RatioFixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RatioFixoMouseClicked(evt);
            }
        });
        getContentPane().add(RatioFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empresa", "CNPJ", "TELEFONE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 960, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarCadastroActionPerformed
        // TODO add your handling code here:
        String telefone = null;
      
        if(RatioCelular.isSelected()){
            tel.CampoFormatado_Telefone.setVisible(false);
                tel.CampoFormatado_Celular.setVisible(true);
            telefone=tel.CampoFormatado_Telefone.getText();
        
        }else if(RatioFixo.isSelected()){
                tel.CampoFormatado_Celular.setVisible(false);
              tel.CampoFormatado_Telefone.setVisible(true);
            telefone=tel.CampoFormatado_Telefone.getText();
        }
        Fornecedor.cadatrarfonnecedor(Jtxt_nome_Empresa.getText(), jFormattedCNPJ.getText(), telefone, jText_Email_Fornecedor.getText(), txt_endereco_fornecedor.getText());
        JOptionPane.showMessageDialog(null, "Dados salvos com sucesso! ");
        Jtxt_nome_Empresa.setText("");
        tel.CampoFormatado_Celular.setText("");
        jText_Email_Fornecedor.setText("");
        jFormattedCNPJ.setText("");
        txt_endereco_fornecedor.setText("");
        
        
    


    }//GEN-LAST:event_btn_salvarCadastroActionPerformed

    private void btb_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_CancelarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btb_CancelarActionPerformed

    private void btn_salvarCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_salvarCadastroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvarCadastroKeyPressed

    private void RatioFixoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RatioFixoFocusGained
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_RatioFixoFocusGained

    private void RatioFixoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RatioFixoFocusLost
        // TODO add your handling code here:
        
         
        
    }//GEN-LAST:event_RatioFixoFocusLost

    private void RatioCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RatioCelularFocusGained
        // TODO add your handling code here:
       
       
        
    }//GEN-LAST:event_RatioCelularFocusGained

    private void RatioCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RatioCelularFocusLost
        // TODO add your handling code here:
        
           
        
    }//GEN-LAST:event_RatioCelularFocusLost

    private void RatioFixoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RatioFixoMouseClicked
        // TODO add your handling code here:
       
        if(RatioFixo.isSelected()){
        RatioFixo.setSelected(true);
        RatioCelular.setSelected(false);
        }
    }//GEN-LAST:event_RatioFixoMouseClicked

    private void RatioCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RatioCelularMouseClicked
        // TODO add your handling code here:
        if(RatioCelular.isSelected()){
        RatioCelular.setSelected(true);
         RatioFixo.setSelected(false);
        }
    }//GEN-LAST:event_RatioCelularMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jtxt_nome_Empresa;
    private javax.swing.JRadioButton RatioCelular;
    private javax.swing.JRadioButton RatioFixo;
    private javax.swing.JButton btb_Cancelar;
    private javax.swing.JButton btn_salvarCadastro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedCNPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText_Email_Fornecedor;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nome_daempresa;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_endereco_fornecedor;
    // End of variables declaration//GEN-END:variables

    int setLocation(int length) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
