/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */


public class CadastraUsuarios extends javax.swing.JInternalFrame {
  
    Usuario usuario=new Usuario();
   
    


    /**
     * Creates new form cadastrausuaruio
     */
    public CadastraUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        label1 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jText_Login = new javax.swing.JTextField();
        jText_Email_user = new javax.swing.JTextField();
        Jtxt_nome_Usuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboPerfil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btb_Cancelar = new javax.swing.JButton();
        btn_salvarCadastro = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPassword_Cadastro = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jFormattedCpf = new javax.swing.JFormattedTextField();
        jPassword_Cadastro1 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Cadastro de Usuário");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("label1");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setText("Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jText_Login.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jText_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 30));

        jText_Email_user.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        getContentPane().add(jText_Email_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 400, 31));

        Jtxt_nome_Usuario.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        getContentPane().add(Jtxt_nome_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 360, 31));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel7.setText("Perfil");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jComboPerfil.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jComboPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Funcionario" }));
        getContentPane().add(jComboPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 130, 32));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel6.setText("Senha");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-male-user-64.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -10, 80, 110));

        btb_Cancelar.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btb_Cancelar.setText("Cancelar");
        btb_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btb_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        btn_salvarCadastro.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btn_salvarCadastro.setText("Salvar");
        btn_salvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarCadastroActionPerformed(evt);
            }
        });
        btn_salvarCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_salvarCadastroKeyPressed(evt);
            }
        });
        getContentPane().add(btn_salvarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 10, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        getContentPane().add(jPassword_Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 130, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel13.setText("CPF");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        try {
            jFormattedCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 160, 30));
        getContentPane().add(jPassword_Cadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 130, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 20, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_LoginActionPerformed
public String  perfil(String perfil){
   for (int i=0;i<usuario.getUsers().size();i++){
       if(usuario.getUsers().get(i).getPerfil().equals(perfil)){
           return usuario.getUsers().get(i).getPerfil();
       }
           
       
   }
   return"";
}
    
    private void btn_salvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarCadastroActionPerformed
        // TODO add your handling code here:
        
     

        String item = "";
        String senha="";
        item=(String) jComboPerfil.getSelectedItem().toString();
        String  var=perfil(item);
        senha=new String (jPassword_Cadastro.getPassword());
        String cpf1=jFormattedCpf.getText();
        String Login =jText_Login.getText();
        String Email=jText_Email_user.getText();
        String cpf2=cpf1;
        cpf2.replace(".","").replace("-","");
        
        if(var.equals("Administrador")){
       
       if(Login.equals("")||(Login==null)||Email.equals("")&&Email==null||cpf2.equals("")||senha.equals("")||senha==null){
           JOptionPane.showMessageDialog(null,"Favor Preencher os campos");
       }else{
        String verifica=usuario.verificarusuario(cpf1);
        System.out.println(verifica);
        
        if(verifica==null||cpf1.equals(verifica)){
       usuario.gravarusuario(Jtxt_nome_Usuario.getText(),jText_Login.getText(),senha,item,jText_Email_user.getText(),jFormattedCpf.getText());
       Jtxt_nome_Usuario.setText("");
        jPassword_Cadastro.setText("");
        jText_Email_user.setText("");
        jText_Login.setText("");
        jFormattedCpf.setText("");
        JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso");
        
        }else{
        Jtxt_nome_Usuario.setText("");
        jPassword_Cadastro.setText("");
        jText_Email_user.setText("");
        jText_Login.setText("");
        jFormattedCpf.setText("");
       JOptionPane.showMessageDialog(null,"Usuário "+Jtxt_nome_Usuario.getText()+" Existe no Sistema");
       
            
        }
       }
      }else if(var.equals("Funcionario")){
           JOptionPane.showMessageDialog(null,"Vocé não nem perfil permitido para esse tipo de registro");
     
        }
           
    
    }//GEN-LAST:event_btn_salvarCadastroActionPerformed

    private void btb_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_CancelarActionPerformed
        // TODO add your handling code here:
        Jtxt_nome_Usuario.setText("");
        jPassword_Cadastro.setText("");
        jText_Email_user.setText("");
        jText_Login.setText("");
         jFormattedCpf.setText("");
        
    }//GEN-LAST:event_btb_CancelarActionPerformed

    private void btn_salvarCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_salvarCadastroKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_btn_salvarCadastroKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jtxt_nome_Usuario;
    private javax.swing.JButton btb_Cancelar;
    private javax.swing.JButton btn_salvarCadastro;
    private javax.swing.JComboBox<String> jComboPerfil;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedCpf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPassword_Cadastro;
    private javax.swing.JPasswordField jPassword_Cadastro1;
    private javax.swing.JTextField jText_Email_user;
    private javax.swing.JTextField jText_Login;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

    int setLocation(int length) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
