/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Model.Fornecedor;
import Model.Usuario;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinic
 */
public class ConsultarFornecedor extends javax.swing.JInternalFrame {

    static int contador = 0;
     Fornecedor forn = new Fornecedor();
     DefaultTableModel dtn=new DefaultTableModel();

    /**
     * Creates new form ConsultarUsuario
     */
    public ConsultarFornecedor() {
        Usuario user = new Usuario();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesquisarFornecedor = new javax.swing.JTable();
        txt_Pesquisa = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Pesquisar Fornecedor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel21.setText("Pesquisar Fornecedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addContainerGap(740, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePesquisarFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da Empresa", "CPF/CNPJ", "Telefone", "Email", "Endereço "
            }
        ));
        jScrollPane1.setViewportView(tablePesquisarFornecedor);

        txt_Pesquisa.setText("Digite o nome ou CPF do Fornecedor");
        txt_Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PesquisaMouseClicked(evt);
            }
        });
        txt_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Pesquisa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        dtn=(DefaultTableModel)tablePesquisarFornecedor.getModel();
        dtn.setRowCount(0);
        txt_Pesquisa.setForeground(Color.gray);
        txt_Pesquisa.setBackground(new Color(255,255,204));
        txt_Pesquisa.setFocusable(false);
        
        for(int i=0;i<forn.getFornecedor().size();i++){
             dtn.addRow(new String[]{forn.getFornecedor().get(i).getNome_da_empresa(),forn.getFornecedor().get(i).getCnpj(),forn.getFornecedor().get(i).getTelefone(),
                 forn.getFornecedor().get(i).getEmail(),forn.getFornecedor().get(i).getEndereco()
                
            });
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void txt_PesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PesquisaMouseClicked
        // TODO add your handling code here:
        txt_Pesquisa.setFocusable(true);
        txt_Pesquisa.setText("");
        
    }//GEN-LAST:event_txt_PesquisaMouseClicked

    private void txt_PesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PesquisaKeyPressed
        // TODO add your handling code here:
        dtn=(DefaultTableModel)tablePesquisarFornecedor.getModel();
        String pesquisa=txt_Pesquisa.getText();
        int quant=pesquisa.length();
        dtn.setRowCount(0);
        
        for(int i=0;i<forn.getFornecedor().size();i++){
            String list=forn.getFornecedor().get(i).getNome_da_empresa().substring(0,quant);
            String list2=forn.getFornecedor().get(i).getCnpj().substring(0,quant);
            
            if(pesquisa.equalsIgnoreCase(list)||pesquisa.equalsIgnoreCase(list2)){
                dtn.addRow(new String[]{forn.getFornecedor().get(i).getNome_da_empresa(),forn.getFornecedor().get(i).getCnpj(),forn.getFornecedor().get(i).getTelefone(),
                 forn.getFornecedor().get(i).getEmail(),forn.getFornecedor().get(i).getEndereco()
                
            });
                
            }
        }
    }//GEN-LAST:event_txt_PesquisaKeyPressed
    public int pesquisa(String pram) {
       

       
      
            if (!forn.getFornecedor().isEmpty()) {

                for (int i = 0; i < forn.getFornecedor().size(); i++) {
                        if (forn.getFornecedor().get(i).getCnpj().equals(pram)) {
                            return i;
                        }
                    }
                }
            

       

        return -1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePesquisarFornecedor;
    private javax.swing.JTextField txt_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
