/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Model.PedidoCompra;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinic
 */
public class ListarPedidosCompra extends javax.swing.JInternalFrame {

    PedidoCompra pedidocompra = new PedidoCompra();

    /**
     * Creates new form ListarPedidosCompra
     */
    public ListarPedidosCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_Pedido_Compra = new javax.swing.JTable();
        btn_Listar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Listagem de Pedidos de Compra");

        tabela_Pedido_Compra.setBackground(new java.awt.Color(255, 255, 204));
        tabela_Pedido_Compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Produto", "Tamnho", "Genero", "Descrição", "Fornecedor", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ));
        jScrollPane3.setViewportView(tabela_Pedido_Compra);

        btn_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-30.png"))); // NOI18N
        btn_Listar.setText("Listar");
        btn_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Listar)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_Listar)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtn = (DefaultTableModel) tabela_Pedido_Compra.getModel();
        for(int i=0;i<pedidocompra.getPedidos().size();i++){

                
                String []dados={""+pedidocompra.getPedidos().get(i).getCodPedido(),pedidocompra.getPedidos().get(i).getNome_Produto(),
                    pedidocompra.getPedidos().get(i).getTamanho(),pedidocompra.getPedidos().get(i).getGenero(),
                    pedidocompra.getPedidos().get(i).getDescricao(),pedidocompra.getPedidos().get(i).getNome_fornecedor(),
                    ""+pedidocompra.getPedidos().get(i).getQtde(),""+pedidocompra.getPedidos().get(i).getValor_Unitario(),
                ""+pedidocompra.getPedidos().get(i).getValor_Total()};
                 dtn.addRow(dados);
            
            
           
        }

    }//GEN-LAST:event_btn_ListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Listar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela_Pedido_Compra;
    // End of variables declaration//GEN-END:variables
}
