/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Model.Usuario;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class Login extends javax.swing.JFrame {

    Usuario usuario = new Usuario();
    static String userperfil = "";

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jtxt_loginentarsistema = new javax.swing.JTextField();
        lblicon = new javax.swing.JLabel();
        lbl_txtareadeacesso = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        jtxt_senha_entrarsistema = new javax.swing.JPasswordField();
        lbl_login = new javax.swing.JLabel();
        btn_limpratxtentrarsistema = new javax.swing.JButton();
        btn_entrarsistema = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T-DRESS SYSTEM");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("T-DRESS SYSTEM LTDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 40));

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1, 7));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 540, 20));

        jPanel3.setBackground(new java.awt.Color(243, 242, 242));

        jtxt_loginentarsistema.setBackground(new java.awt.Color(255, 255, 204));
        jtxt_loginentarsistema.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxt_loginentarsistema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), null, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 204)));

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/multiplos-usuarios 64.png"))); // NOI18N

        lbl_txtareadeacesso.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_txtareadeacesso.setText("Area de Acesso");

        lblsenha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblsenha.setText("Senha");

        jtxt_senha_entrarsistema.setBackground(new java.awt.Color(255, 255, 204));
        jtxt_senha_entrarsistema.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxt_senha_entrarsistema.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), null, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 204)));
        jtxt_senha_entrarsistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_senha_entrarsistemaActionPerformed(evt);
            }
        });
        jtxt_senha_entrarsistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_senha_entrarsistemaKeyReleased(evt);
            }
        });

        lbl_login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_login.setText("Login");

        btn_limpratxtentrarsistema.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_limpratxtentrarsistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vassoura.png"))); // NOI18N
        btn_limpratxtentrarsistema.setBorder(null);
        btn_limpratxtentrarsistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpratxtentrarsistemaActionPerformed(evt);
            }
        });

        btn_entrarsistema.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_entrarsistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entrada.png"))); // NOI18N
        btn_entrarsistema.setBorder(null);
        btn_entrarsistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarsistemaActionPerformed(evt);
            }
        });
        btn_entrarsistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_entrarsistemaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_login)
                            .addComponent(lblsenha))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_loginentarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_senha_entrarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_entrarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(lbl_txtareadeacesso)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblicon)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_limpratxtentrarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_txtareadeacesso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_login, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_loginentarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_senha_entrarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_limpratxtentrarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_entrarsistema, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 530, 290));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 530, 250));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 100, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_senha_entrarsistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_senha_entrarsistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_senha_entrarsistemaActionPerformed
    public String perfil(String login) {
        if (!usuario.getUsers().isEmpty()) {
            for (int i = 0; i < usuario.getUsers().size(); i++) {

                if (usuario.getUsers().get(i).getLogin().equals(login)) {

                    userperfil = usuario.getUsers().get(i).getPerfil();
                   
                    return usuario.getUsers().get(i).getPerfil();

                }

            }

        }
        return null;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
      
       btn_entrarsistema.setContentAreaFilled(false);
       // btn_entrarsistema.setOpaque(true);
        btn_entrarsistema.setBackground(Color.WHITE);
        
        
        btn_limpratxtentrarsistema.setContentAreaFilled(false);
       // btn_limpratxtentrarsistema.setOpaque(true);
        btn_limpratxtentrarsistema.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_formWindowOpened
 
    private void btn_entrarsistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarsistemaActionPerformed
        // TODO add your handling code here:
       
             
        String senha = new String(jtxt_senha_entrarsistema.getPassword());
        String entrar = usuario.verificarus(jtxt_loginentarsistema.getText().trim(), senha.trim());
        String verificauser=perfil(jtxt_loginentarsistema.getText());

        if (entrar.equals("encontrado")) {
            jtxt_loginentarsistema.setText("");
            jtxt_senha_entrarsistema.setText("");
            this.setVisible(false);
            TelaPrincipal telaprincipal = new TelaPrincipal();
            telaprincipal.setVisible(true);

        } else {

            jtxt_loginentarsistema.setText("");
            jtxt_senha_entrarsistema.setText("");
            jtxt_loginentarsistema.setCursor(java.awt.Cursor.getDefaultCursor());
            jtxt_senha_entrarsistema.setFocusable(true);
            JOptionPane.showMessageDialog(null, "Usúario Incorreto !!!");
            btn_entrarsistema.setFocusable(false);
             jtxt_loginentarsistema.setFocusable(true);
             jtxt_senha_entrarsistema.setFocusable(false);
        }
        
       btn_entrarsistema.setFocusable(true);
        jtxt_senha_entrarsistema.setFocusable(true);
    }//GEN-LAST:event_btn_entrarsistemaActionPerformed

    private void btn_limpratxtentrarsistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpratxtentrarsistemaActionPerformed
        // TODO add your handling code here:
        String senha=new String (jtxt_senha_entrarsistema.getPassword());
        String login=jtxt_loginentarsistema.getText();

        if(!login.equals("")&&(!senha.equals(""))){// Limpar Campos de Login e Senha

            jtxt_loginentarsistema.setText("");
            jtxt_senha_entrarsistema.setText("");
        }
    }//GEN-LAST:event_btn_limpratxtentrarsistemaActionPerformed

    private void jtxt_senha_entrarsistemaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_senha_entrarsistemaKeyReleased
            // TODO add your handling code here:
             jtxt_loginentarsistema.setFocusable(true);
             jtxt_senha_entrarsistema.setFocusable(true);
             if(evt.getKeyCode()==evt.VK_ENTER){
            String senha = new String(jtxt_senha_entrarsistema.getPassword());
        String entrar = usuario.verificarus(jtxt_loginentarsistema.getText().trim(), senha.trim());
        String verificauser=perfil(jtxt_loginentarsistema.getText());

        if (entrar.equals("encontrado")) {
            jtxt_loginentarsistema.setText("");
            jtxt_senha_entrarsistema.setText("");
            this.setVisible(false);
            TelaPrincipal telaprincipal = new TelaPrincipal();
            telaprincipal.setVisible(true);

        } else {

            jtxt_loginentarsistema.setText("");
            jtxt_senha_entrarsistema.setText("");
            JOptionPane.showMessageDialog(null, "\n       Usúario Incorreto!");
            jtxt_senha_entrarsistema.setFocusable(false);
            jtxt_loginentarsistema.setFocusable(true);
        }
             }
              jtxt_loginentarsistema.setFocusable(true);
             jtxt_senha_entrarsistema.setFocusable(true);
            
    }//GEN-LAST:event_jtxt_senha_entrarsistemaKeyReleased

    private void btn_entrarsistemaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_entrarsistemaKeyReleased
        // TODO add your handling code here:
        
       
        
        
    }//GEN-LAST:event_btn_entrarsistemaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrarsistema;
    private javax.swing.JButton btn_limpratxtentrarsistema;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jtxt_loginentarsistema;
    private javax.swing.JPasswordField jtxt_senha_entrarsistema;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_txtareadeacesso;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblsenha;
    // End of variables declaration//GEN-END:variables

}
