/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import Model.Usuario;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.FileDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author vinic
 */
public class TelaPrincipal extends javax.swing.JFrame {

    GerarIntenalFrameCentralizado InternalframeCentralizado = new GerarIntenalFrameCentralizado();
    Login login = new Login();
    CadastarFornecedor cadastrofornecedor = new CadastarFornecedor();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        desktopPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_hora = new javax.swing.JLabel();
        lbl_data1 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_CadastrarUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_alterarSenhaUser = new javax.swing.JButton();
        btn_cadastrarForn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_ConsultarFornecedor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_CadastrarPedido = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_ConsultarPedido = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_ListarPedido = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_cadastrarclientes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ConsultarCliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu_Usuario = new javax.swing.JMenu();
        jMenuItem_Usuario_Cadastrar = new javax.swing.JMenuItem();
        jMenu_Usuario_consultar = new javax.swing.JMenuItem();
        jMenu_Usuario_Listar = new javax.swing.JMenuItem();
        jMenuItem_Usuario_AlterarSenha = new javax.swing.JMenuItem();
        jMenu_Usuario_Excluir = new javax.swing.JMenuItem();
        jMenu_Fornecedor = new javax.swing.JMenu();
        jMenuItem_Fornecedor_Cadastrar = new javax.swing.JMenuItem();
        jMenuItem_Fornecedor_Consultar = new javax.swing.JMenuItem();
        jMenu_Fornecedo_Listar = new javax.swing.JMenuItem();
        jMenuItem_Fornecedor_Alterar = new javax.swing.JMenuItem();
        jMenuItem_Fornecedor_Excluir = new javax.swing.JMenuItem();
        jMenu_PedidoCompra = new javax.swing.JMenu();
        jMenuItem_PedidoCompra_Cadastrar = new javax.swing.JMenuItem();
        jMenuItem_PedidoCompra_Consultar = new javax.swing.JMenuItem();
        JMenu_item_PedidoCompra_Listar = new javax.swing.JMenuItem();
        jMenuItem_PedidoCompra_Alterar = new javax.swing.JMenuItem();
        jMenuItem_PedidoCompra_Excluir = new javax.swing.JMenuItem();
        jMenu_Estoque = new javax.swing.JMenu();
        jMenu_Estoque_consultar = new javax.swing.JMenuItem();
        jMenu_Cliente = new javax.swing.JMenu();
        jMenuItem_Cliente_Cadastrar = new javax.swing.JMenuItem();
        jMenuItem_Cliente_Consultar = new javax.swing.JMenuItem();
        jMenuItem_Cliente_Alterar = new javax.swing.JMenuItem();
        jMenuItem_Cliente_Excluir = new javax.swing.JMenuItem();
        jMenu_Vendas = new javax.swing.JMenu();
        jMenuItem_Vendas_Vender = new javax.swing.JMenuItem();
        jMenuItem_Vendas_Consultar = new javax.swing.JMenuItem();
        jMenuItem_Vendas_Alterar = new javax.swing.JMenuItem();
        jMenuItem_Vendas_Excluir = new javax.swing.JMenuItem();
        jMenu_Ajuda = new javax.swing.JMenu();
        jMenuItem_Ajuda_Sobre = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem15.setText("jMenuItem15");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Roupa T-DRESS LTDA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktopPrincipal.setBackground(new java.awt.Color(242, 242, 255));
        desktopPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        desktopPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${size.height}"), desktopPrincipal, org.jdesktop.beansbinding.BeanProperty.create("minimumSize"));
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_hora.setFont(new java.awt.Font("News701 BT", 0, 17)); // NOI18N
        lbl_hora.setForeground(new java.awt.Color(0, 0, 153));

        lbl_data1.setFont(new java.awt.Font("News701 BT", 0, 17)); // NOI18N
        lbl_data1.setForeground(new java.awt.Color(0, 0, 153));

        lbl_user.setFont(new java.awt.Font("News701 BT", 0, 17)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(0, 0, 153));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(lbl_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lbl_data1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(lbl_hora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lbl_user, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lbl_data1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lbl_hora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_CadastrarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btn_CadastrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_CadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/equipe (1).png"))); // NOI18N
        btn_CadastrarUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cadastrar Usuário");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Alterar Senha");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_alterarSenhaUser.setBackground(new java.awt.Color(255, 255, 255));
        btn_alterarSenhaUser.setForeground(new java.awt.Color(255, 255, 255));
        btn_alterarSenhaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seguranca.png"))); // NOI18N
        btn_alterarSenhaUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_cadastrarForn.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadastrarForn.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrarForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fornecedor.png"))); // NOI18N
        btn_cadastrarForn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cadastrarForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarFornActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Cadastrar Fornecedor");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ConsultarFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        btn_ConsultarFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        btn_ConsultarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ceo.png"))); // NOI18N
        btn_ConsultarFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarFornecedorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Consultar Fornecedor");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_CadastrarPedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_CadastrarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btn_CadastrarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comprar.png"))); // NOI18N
        btn_CadastrarPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_CadastrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarPedidoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cadastrar Pedido ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ConsultarPedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_ConsultarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btn_ConsultarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fabrica.png"))); // NOI18N
        btn_ConsultarPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarPedidoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("   Estoque");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ListarPedido.setBackground(new java.awt.Color(255, 255, 255));
        btn_ListarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btn_ListarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ordem.png"))); // NOI18N
        btn_ListarPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_ListarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarPedidoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cadastrar Cliente");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_cadastrarclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        btn_cadastrarclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarclientesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Listar Pedidos");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/procurar.png"))); // NOI18N
        ConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Consultar Cliente");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btn_CadastrarUsuario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btn_alterarSenhaUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btn_cadastrarForn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btn_ConsultarFornecedor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btn_CadastrarPedido, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btn_ConsultarPedido, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btn_ListarPedido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btn_cadastrarclientes)
                    .add(jLabel7))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10)
                    .add(ConsultarCliente))
                .addContainerGap(721, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btn_alterarSenhaUser)
            .add(jPanel3Layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(btn_CadastrarUsuario)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, ConsultarCliente))
                            .add(btn_ConsultarPedido))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel8)
                            .add(jLabel9)
                            .add(jLabel7)
                            .add(jLabel10)))
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(btn_cadastrarForn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btn_ConsultarFornecedor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btn_CadastrarPedido, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btn_ListarPedido, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btn_cadastrarclientes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        desktopPrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPrincipal.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout desktopPrincipalLayout = new org.jdesktop.layout.GroupLayout(desktopPrincipal);
        desktopPrincipal.setLayout(desktopPrincipalLayout);
        desktopPrincipalLayout.setHorizontalGroup(
            desktopPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(desktopPrincipalLayout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .add(0, 0, Short.MAX_VALUE))
        );
        desktopPrincipalLayout.setVerticalGroup(
            desktopPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, desktopPrincipalLayout.createSequentialGroup()
                .add(desktopPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 705, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jMenu_Usuario.setText("Usuario");
        jMenu_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_UsuarioActionPerformed(evt);
            }
        });

        jMenuItem_Usuario_Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Usuario_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-adicionar-livro-36.png"))); // NOI18N
        jMenuItem_Usuario_Cadastrar.setText("Cadastrar");
        jMenuItem_Usuario_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Usuario_CadastrarActionPerformed(evt);
            }
        });
        jMenu_Usuario.add(jMenuItem_Usuario_Cadastrar);

        jMenu_Usuario_consultar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu_Usuario_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-mais-36.png"))); // NOI18N
        jMenu_Usuario_consultar.setText("Consultar");
        jMenu_Usuario_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Usuario_consultarActionPerformed(evt);
            }
        });
        jMenu_Usuario.add(jMenu_Usuario_consultar);

        jMenu_Usuario_Listar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu_Usuario_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lista-de-tarefas-36.png"))); // NOI18N
        jMenu_Usuario_Listar.setText("Listar");
        jMenu_Usuario_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Usuario_ListarActionPerformed(evt);
            }
        });
        jMenu_Usuario.add(jMenu_Usuario_Listar);

        jMenuItem_Usuario_AlterarSenha.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Usuario_AlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-conta-36.png"))); // NOI18N
        jMenuItem_Usuario_AlterarSenha.setText("Alterar senha");
        jMenu_Usuario.add(jMenuItem_Usuario_AlterarSenha);

        jMenu_Usuario_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu_Usuario_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-36.png"))); // NOI18N
        jMenu_Usuario_Excluir.setText("Excluir");
        jMenu_Usuario.add(jMenu_Usuario_Excluir);

        Menu.add(jMenu_Usuario);

        jMenu_Fornecedor.setText("Fornecedor");
        jMenu_Fornecedor.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem_Fornecedor_Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Fornecedor_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-adicionar-livro-36.png"))); // NOI18N
        jMenuItem_Fornecedor_Cadastrar.setText("Cadastrar");
        jMenuItem_Fornecedor_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Fornecedor_CadastrarActionPerformed(evt);
            }
        });
        jMenu_Fornecedor.add(jMenuItem_Fornecedor_Cadastrar);

        jMenuItem_Fornecedor_Consultar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Fornecedor_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-mais-36.png"))); // NOI18N
        jMenuItem_Fornecedor_Consultar.setText("Consultar");
        jMenuItem_Fornecedor_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Fornecedor_ConsultarActionPerformed(evt);
            }
        });
        jMenu_Fornecedor.add(jMenuItem_Fornecedor_Consultar);

        jMenu_Fornecedo_Listar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu_Fornecedo_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lista-de-tarefas-36.png"))); // NOI18N
        jMenu_Fornecedo_Listar.setText("Listar");
        jMenu_Fornecedo_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Fornecedo_ListarActionPerformed(evt);
            }
        });
        jMenu_Fornecedor.add(jMenu_Fornecedo_Listar);

        jMenuItem_Fornecedor_Alterar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Fornecedor_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-conta-36.png"))); // NOI18N
        jMenuItem_Fornecedor_Alterar.setText("Alterar");
        jMenu_Fornecedor.add(jMenuItem_Fornecedor_Alterar);

        jMenuItem_Fornecedor_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Fornecedor_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-36.png"))); // NOI18N
        jMenuItem_Fornecedor_Excluir.setText("Excluir");
        jMenu_Fornecedor.add(jMenuItem_Fornecedor_Excluir);

        Menu.add(jMenu_Fornecedor);

        jMenu_PedidoCompra.setText("Pedido de Compra");
        jMenu_PedidoCompra.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem_PedidoCompra_Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_PedidoCompra_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-adicionar-livro-36.png"))); // NOI18N
        jMenuItem_PedidoCompra_Cadastrar.setText("Cadastrar");
        jMenuItem_PedidoCompra_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidoCompra_CadastrarActionPerformed(evt);
            }
        });
        jMenu_PedidoCompra.add(jMenuItem_PedidoCompra_Cadastrar);

        jMenuItem_PedidoCompra_Consultar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_PedidoCompra_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-mais-36.png"))); // NOI18N
        jMenuItem_PedidoCompra_Consultar.setText("Consultar");
        jMenuItem_PedidoCompra_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidoCompra_ConsultarActionPerformed(evt);
            }
        });
        jMenu_PedidoCompra.add(jMenuItem_PedidoCompra_Consultar);

        JMenu_item_PedidoCompra_Listar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        JMenu_item_PedidoCompra_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lista-de-tarefas-36.png"))); // NOI18N
        JMenu_item_PedidoCompra_Listar.setText("Listar");
        JMenu_item_PedidoCompra_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu_item_PedidoCompra_ListarActionPerformed(evt);
            }
        });
        jMenu_PedidoCompra.add(JMenu_item_PedidoCompra_Listar);

        jMenuItem_PedidoCompra_Alterar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_PedidoCompra_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-editar-conta-36.png"))); // NOI18N
        jMenuItem_PedidoCompra_Alterar.setText("Alterar");
        jMenu_PedidoCompra.add(jMenuItem_PedidoCompra_Alterar);

        jMenuItem_PedidoCompra_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_PedidoCompra_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-excluir-36.png"))); // NOI18N
        jMenuItem_PedidoCompra_Excluir.setText("Excluir");
        jMenuItem_PedidoCompra_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PedidoCompra_ExcluirActionPerformed(evt);
            }
        });
        jMenu_PedidoCompra.add(jMenuItem_PedidoCompra_Excluir);

        Menu.add(jMenu_PedidoCompra);

        jMenu_Estoque.setText("Estoque");
        jMenu_Estoque.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenu_Estoque_consultar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu_Estoque_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-light-automation-30.png"))); // NOI18N
        jMenu_Estoque_consultar.setText("Controlar Estoque");
        jMenu_Estoque_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_Estoque_consultarActionPerformed(evt);
            }
        });
        jMenu_Estoque.add(jMenu_Estoque_consultar);

        Menu.add(jMenu_Estoque);

        jMenu_Cliente.setText("Cliente");
        jMenu_Cliente.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem_Cliente_Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Cliente_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-adicionar-livro-36.png"))); // NOI18N
        jMenuItem_Cliente_Cadastrar.setText("Cadastrar");
        jMenuItem_Cliente_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Cliente_CadastrarActionPerformed(evt);
            }
        });
        jMenu_Cliente.add(jMenuItem_Cliente_Cadastrar);

        jMenuItem_Cliente_Consultar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Cliente_Consultar.setText("Consultar");
        jMenuItem_Cliente_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Cliente_ConsultarActionPerformed(evt);
            }
        });
        jMenu_Cliente.add(jMenuItem_Cliente_Consultar);

        jMenuItem_Cliente_Alterar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Cliente_Alterar.setText("Alterar");
        jMenu_Cliente.add(jMenuItem_Cliente_Alterar);

        jMenuItem_Cliente_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Cliente_Excluir.setText("Excluir");
        jMenu_Cliente.add(jMenuItem_Cliente_Excluir);

        Menu.add(jMenu_Cliente);

        jMenu_Vendas.setText("Vendas");
        jMenu_Vendas.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem_Vendas_Vender.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Vendas_Vender.setText("Vender");
        jMenu_Vendas.add(jMenuItem_Vendas_Vender);

        jMenuItem_Vendas_Consultar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Vendas_Consultar.setText("Consultar");
        jMenuItem_Vendas_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Vendas_ConsultarActionPerformed(evt);
            }
        });
        jMenu_Vendas.add(jMenuItem_Vendas_Consultar);

        jMenuItem_Vendas_Alterar.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Vendas_Alterar.setText("Alterar");
        jMenu_Vendas.add(jMenuItem_Vendas_Alterar);

        jMenuItem_Vendas_Excluir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Vendas_Excluir.setText("Excluir");
        jMenu_Vendas.add(jMenuItem_Vendas_Excluir);

        Menu.add(jMenu_Vendas);

        jMenu_Ajuda.setText("Ajuda");
        jMenu_Ajuda.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jMenuItem_Ajuda_Sobre.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem_Ajuda_Sobre.setText("Sobre");
        jMenuItem_Ajuda_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Ajuda_SobreActionPerformed(evt);
            }
        });
        jMenu_Ajuda.add(jMenuItem_Ajuda_Sobre);

        Menu.add(jMenu_Ajuda);

        Sair.setText("Sair");
        Sair.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Menu.add(Sair);

        setJMenuBar(Menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPrincipal)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Usuario_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Usuario_CadastrarActionPerformed
        // TODO add your handling code here:
        
     
        
        

       
        InternalframeCentralizado.gerarcental(new CadastraUsuarios(), desktopPrincipal);
        
        
       


    }//GEN-LAST:event_jMenuItem_Usuario_CadastrarActionPerformed

    private void jMenuItem_PedidoCompra_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidoCompra_ConsultarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new ConsultarPedidoCompra(), desktopPrincipal);
    }//GEN-LAST:event_jMenuItem_PedidoCompra_ConsultarActionPerformed

    private void jMenuItem_Vendas_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Vendas_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_Vendas_ConsultarActionPerformed

    private void jMenu_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_UsuarioActionPerformed

    private void jMenuItem_PedidoCompra_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidoCompra_ExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_PedidoCompra_ExcluirActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
     // TODO add your handling code here:
     TelaPrincipal tel=new TelaPrincipal();
   
   
     if(Sair.isFocusable()){
      
  
     
     this.dispose();  
     }

    }//GEN-LAST:event_SairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:     

        Login log = new Login();
        btn_CadastrarUsuario.setContentAreaFilled(false);
        btn_CadastrarUsuario.setOpaque(true);
        btn_CadastrarUsuario.setBackground(Color.WHITE);
        btn_alterarSenhaUser.setContentAreaFilled(false);
        btn_alterarSenhaUser.setOpaque(true);
        btn_alterarSenhaUser.setBackground(Color.WHITE);

        btn_cadastrarForn.setContentAreaFilled(false);
        btn_cadastrarForn.setOpaque(true);
        btn_cadastrarForn.setBackground(Color.WHITE);
        
        btn_CadastrarPedido.setContentAreaFilled(false);
        btn_CadastrarPedido.setOpaque(true);
        btn_CadastrarPedido.setBackground(Color.WHITE);
        
        btn_ConsultarPedido.setContentAreaFilled(false);
        btn_ConsultarPedido.setOpaque(true);
        btn_ConsultarPedido.setBackground(Color.WHITE);
        
         btn_ConsultarFornecedor.setContentAreaFilled(false);
        btn_ConsultarFornecedor.setOpaque(true);
        btn_ConsultarFornecedor.setBackground(Color.WHITE);
        
         btn_ListarPedido.setContentAreaFilled(false);
        btn_ListarPedido.setOpaque(true);
        btn_ListarPedido.setBackground(Color.WHITE);
        
        btn_cadastrarclientes.setContentAreaFilled(false);
        btn_cadastrarclientes.setOpaque(true);
        btn_cadastrarclientes.setBackground(Color.WHITE);
        

        lbl_user.setText(log.userperfil);
        if (log.userperfil.equals("Funcionario")) {
            jMenu_Usuario.setEnabled(false);
            jMenuItem_Fornecedor_Cadastrar.setEnabled(false);
            jMenu_Fornecedo_Listar.setEnabled(false);
            jMenuItem_Fornecedor_Alterar.setEnabled(false);
            jMenuItem_Fornecedor_Excluir.setEnabled(false);
            jMenu_PedidoCompra.setEnabled(false);

        }

        Date dt = new Date();
        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
        lbl_data1.setText(ff.format(dt));

        Timer timer = new Timer(1000, new hora());
        timer.start();

    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem_Fornecedor_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Fornecedor_CadastrarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new CadastarFornecedor(), desktopPrincipal);
    }//GEN-LAST:event_jMenuItem_Fornecedor_CadastrarActionPerformed

    private void jMenu_Usuario_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Usuario_consultarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new consultausuario(), desktopPrincipal);
    }//GEN-LAST:event_jMenu_Usuario_consultarActionPerformed

    private void jMenuItem_Fornecedor_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Fornecedor_ConsultarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new ConsultarFornecedor(), desktopPrincipal);
    }//GEN-LAST:event_jMenuItem_Fornecedor_ConsultarActionPerformed

    private void jMenu_Fornecedo_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Fornecedo_ListarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new ExibirFornecedor(), desktopPrincipal);
    }//GEN-LAST:event_jMenu_Fornecedo_ListarActionPerformed

    private void jMenu_Usuario_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Usuario_ListarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new ExibirUsuarios(), desktopPrincipal);
    }//GEN-LAST:event_jMenu_Usuario_ListarActionPerformed

    private void jMenuItem_PedidoCompra_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PedidoCompra_CadastrarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new CadastrarPedidoCompra(), desktopPrincipal);
    }//GEN-LAST:event_jMenuItem_PedidoCompra_CadastrarActionPerformed

    private void JMenu_item_PedidoCompra_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu_item_PedidoCompra_ListarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new ListarPedidosCompra(), desktopPrincipal);
    }//GEN-LAST:event_JMenu_item_PedidoCompra_ListarActionPerformed

    private void jMenu_Estoque_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_Estoque_consultarActionPerformed
        // TODO add your handling code here:
        InternalframeCentralizado.gerarcental(new ControlarEstoque(), desktopPrincipal);
    }//GEN-LAST:event_jMenu_Estoque_consultarActionPerformed

    private void jMenuItem_Ajuda_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Ajuda_SobreActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(new File("C:\\Users\\vinic\\OneDrive\\Área de Trabalho\\FAESA\\NetBeansProjects\\T-DRESS\\tdress.pdf"));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem_Ajuda_SobreActionPerformed

    private void btn_ConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarPedidoActionPerformed
        // TODO add your handling code here:
        jMenuItem_PedidoCompra_ConsultarActionPerformed(evt);
    }//GEN-LAST:event_btn_ConsultarPedidoActionPerformed

    private void btn_CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarUsuarioActionPerformed
        // TODO add your handling code here:
         InternalframeCentralizado.gerarcental(new consultausuario(), desktopPrincipal);
        
    }//GEN-LAST:event_btn_CadastrarUsuarioActionPerformed

    private void jMenuItem_Cliente_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Cliente_CadastrarActionPerformed
        // TODO add your handling code here:
          InternalframeCentralizado.gerarcental(new CadastrarCliente(), desktopPrincipal);
    }//GEN-LAST:event_jMenuItem_Cliente_CadastrarActionPerformed

    private void jMenuItem_Cliente_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Cliente_ConsultarActionPerformed
        // TODO add your handling code here:
           InternalframeCentralizado.gerarcental(new ConsultarCliente(), desktopPrincipal);
    }//GEN-LAST:event_jMenuItem_Cliente_ConsultarActionPerformed

    private void btn_cadastrarFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarFornActionPerformed
        // TODO add your handling code here:
        jMenuItem_Fornecedor_CadastrarActionPerformed(evt);
    }//GEN-LAST:event_btn_cadastrarFornActionPerformed

    private void btn_ConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarFornecedorActionPerformed
        // TODO add your handling code here:
        jMenuItem_Fornecedor_ConsultarActionPerformed(evt);
      
    }//GEN-LAST:event_btn_ConsultarFornecedorActionPerformed

    private void btn_CadastrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarPedidoActionPerformed
        // TODO add your handling code here:
         jMenuItem_PedidoCompra_CadastrarActionPerformed(evt);
      
    }//GEN-LAST:event_btn_CadastrarPedidoActionPerformed

    private void btn_ListarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarPedidoActionPerformed
        // TODO add your handling code here:
        JMenu_item_PedidoCompra_ListarActionPerformed(evt);
        
       
    }//GEN-LAST:event_btn_ListarPedidoActionPerformed

    private void btn_cadastrarclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarclientesActionPerformed
        // TODO add your handling code here:
        jMenuItem_Cliente_CadastrarActionPerformed(evt);
        
    }//GEN-LAST:event_btn_cadastrarclientesActionPerformed

    private void ConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarClienteActionPerformed
        // TODO add your handling code here:
        jMenuItem_Cliente_ConsultarActionPerformed(evt);
       
    }//GEN-LAST:event_ConsultarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarCliente;
    public javax.swing.JMenuItem JMenu_item_PedidoCompra_Listar;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Sair;
    private javax.swing.JButton btn_CadastrarPedido;
    private javax.swing.JButton btn_CadastrarUsuario;
    private javax.swing.JButton btn_ConsultarFornecedor;
    private javax.swing.JButton btn_ConsultarPedido;
    private javax.swing.JButton btn_ListarPedido;
    private javax.swing.JButton btn_alterarSenhaUser;
    private javax.swing.JButton btn_cadastrarForn;
    private javax.swing.JButton btn_cadastrarclientes;
    public static javax.swing.JDesktopPane desktopPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem_Ajuda_Sobre;
    private javax.swing.JMenuItem jMenuItem_Cliente_Alterar;
    public javax.swing.JMenuItem jMenuItem_Cliente_Cadastrar;
    public javax.swing.JMenuItem jMenuItem_Cliente_Consultar;
    private javax.swing.JMenuItem jMenuItem_Cliente_Excluir;
    public javax.swing.JMenuItem jMenuItem_Fornecedor_Alterar;
    public javax.swing.JMenuItem jMenuItem_Fornecedor_Cadastrar;
    public javax.swing.JMenuItem jMenuItem_Fornecedor_Consultar;
    public javax.swing.JMenuItem jMenuItem_Fornecedor_Excluir;
    public javax.swing.JMenuItem jMenuItem_PedidoCompra_Alterar;
    public javax.swing.JMenuItem jMenuItem_PedidoCompra_Cadastrar;
    public javax.swing.JMenuItem jMenuItem_PedidoCompra_Consultar;
    public javax.swing.JMenuItem jMenuItem_PedidoCompra_Excluir;
    private javax.swing.JMenuItem jMenuItem_Usuario_AlterarSenha;
    private javax.swing.JMenuItem jMenuItem_Usuario_Cadastrar;
    private javax.swing.JMenuItem jMenuItem_Vendas_Alterar;
    private javax.swing.JMenuItem jMenuItem_Vendas_Consultar;
    private javax.swing.JMenuItem jMenuItem_Vendas_Excluir;
    private javax.swing.JMenuItem jMenuItem_Vendas_Vender;
    private javax.swing.JMenu jMenu_Ajuda;
    private javax.swing.JMenu jMenu_Cliente;
    private javax.swing.JMenu jMenu_Estoque;
    private javax.swing.JMenuItem jMenu_Estoque_consultar;
    public javax.swing.JMenuItem jMenu_Fornecedo_Listar;
    public javax.swing.JMenu jMenu_Fornecedor;
    private javax.swing.JMenu jMenu_PedidoCompra;
    private javax.swing.JMenu jMenu_Usuario;
    private javax.swing.JMenuItem jMenu_Usuario_Excluir;
    private javax.swing.JMenuItem jMenu_Usuario_Listar;
    private javax.swing.JMenuItem jMenu_Usuario_consultar;
    private javax.swing.JMenu jMenu_Vendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_data1;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_user;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Date dtt = new Date();
            Calendar now = Calendar.getInstance();
            lbl_hora.setText(String.format("%1$tH:%1$tM:%1$tS", now));

        }
    }
}
